version: "3.8"

services:
  store:
    container_name: store
    build:
      context: .
      dockerfile: ./docker/store/Dockerfile
    volumes:
      - ./store:/app
    networks:
      - timing
      - entry
      - main_network
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db_store
      - redis
    environment:
      DB_NAME: "store"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db_store"
      DB_PORT: "5432"
      DJANGO_ENV: "dev"
    restart: on-failure
    command:
      - sh /runserver.sh

  warehouse:
    container_name: warehouse
    build:
      context: .
      dockerfile: ./docker/warehouse/Dockerfile
    volumes:
      - ./warehouse:/app
    networks:
      - warehouse_db_network
      - timing
      - entry
      - notifications
    expose:
      - 8001
    ports:
      - "8001:8001"
    depends_on:
      - db_warehouse
    environment:
      DB_NAME: "warehouse"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db_warehouse"
      DB_PORT: "5432"
    restart: on-failure
    command:
      - sh /runserver.sh

  db_store:
    container_name: db_store
    image: postgres:14-alpine
    volumes:
      - db_store:/var/lib/postgresql/data
    networks:
      - main_network
    expose:
      - 5432
    restart: on-failure
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'store'

  db_warehouse:
    container_name: db_warehouse
    image: postgres:14-alpine
    volumes:
      - db_warehouse:/var/lib/postgresql/data
    networks:
      - warehouse_db_network
    expose:
      - 5432
    restart: on-failure
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'warehouse'

  web:
    container_name: nginx
    image: nginx
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf/custom.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mailhog
      - warehouse
      - store


  celery:
    container_name: celery
    build:
      context: .
      dockerfile: docker/store/Dockerfile
      args:
        DJANGO_ENV: 'dev'
    networks:
      - timing
      - notifications
      - main_network
    expose:
      - 8000
    volumes:
      - ./store:/code
      - ./config:/config
    environment:
      C_FORCE_ROOT: 'true'
      DATABASE_URL: 'postgresql://postgres:postgdb@db_store:5432/store'
      DATABASE_HOST: 'db_store'
      DATABASE_PORT: '5432'
      REDIS_URL: 'redis://redis:6379/0'
      REDIS_CACHE: 'redis:6379'
      AMQP_URL: 'amqp://rabbitmq:5672'
#      WEB_HOST: 'store'
#      WEB_PORT: '8000'
    depends_on:
      - rabbitmq
      - db_store
    restart: on-failure
    command: celery -A store worker -B -l INFO

  redis:
    container_name: redis
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    networks:
      - main_network
    volumes:
      - redis:/var/lib/redis/data

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    command: [ "-smtp-bind-addr", "0.0.0.0:25" ]
    user: root
    restart: on-failure
    networks:
      - entry
      - notifications
    expose:
      - 25
      - 8025

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    expose:
      - 4369
      - 5671
      - 5672
      - 15672
      - 25672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - main_network

networks:
  warehouse_db_network:
  timing:
  entry:
  notifications:
  main_network:

volumes:
  db_store:
  db_warehouse:
  redis:
  rabbitmq_data: