# Generated by Django 4.1.1 on 2022-09-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='author',
            name='deathdate',
        ),
    ]
